#!/usr/bin/env ruby
# File: script/console
irb = 'irb'

libs =  " -r irb/completion"
# Perhaps use a console_lib to store any extra methods I may want available in the cosole
# libs << " -r #{File.dirname(__FILE__) + '/../lib/console_lib/console_logger.rb'}"
libs <<  " -r commit_stats"
puts "Loading commit_stats gem"
exec "#{irb} -I lib #{libs} --simple-prompt"
